### ISSUE TITLE
ERROR in ./buildScripts/entrypoints/Covid.mjs

### ISSUE THREAD

**Issue by lgallard** [neomjs/covid-dashboard#3]
Following the README instructions:

```
$ git clone https://github.com/neomjs/covid-dashboard.git
$ cd covid-dashboard
$ npm run build-all

...
[27] ./node_modules/neo.mjs/src/worker/Data.mjs + 3 modules 9.92 KiB {2} [built]
     |    4 modules
[28] ./node_modules/neo.mjs/src/worker/VDom.mjs + 2 modules 28.6 KiB {4} [built]
     |    3 modules
[29] ./node_modules/neo.mjs/src/tooltip/Base.mjs + 1 modules 7.94 KiB {5} [built]
     |    2 modules
    + 18 hidden modules

ERROR in ./buildScripts/entrypoints/Covid.mjs
Module not found: Error: Can't resolve '../../apps/Covid/app.mjs' in '/home/lgallard/git/covid-dashboard/buildScripts/entrypoints'
 @ ./buildScripts/entrypoints/Covid.mjs 2:0-34
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! covid19-dashboard@1.0.14 prod-build-all-my-apps: `webpack --config ./node_modules/neo.mjs/buildScripts/webpack/production/webpack.config.myapps.js --env.build_all=true`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the covid19-dashboard@1.0.14 prod-build-all-my-apps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lgallard/.npm/_logs/2020-04-20T22_28_58_607Z-debug.log

```

Any idea?

**Comment by MaJingRui-SH** [comment]
Goto buildScripts/entrypoints and edit Covid.mjs

Change '../../apps/Covid/app.mjs' to '../../apps/covid/app.mjs'

**Comment by tobiu** [comment]
ha, if you know of this one, where is the PR? :)

pushed a fix here, this has to be inside the npx neo-app repo. double-checking.

**Comment by tobiu** [comment]
ok, adjusted it inside the npx repo & updated this one to the latest neo version.
there is still an error, since the build dev & prod framework tasks are not included here.

on purpose, since those build the framework examples which are not needed here, but still there should be a check if the files exist. the build app task covers the worker builds.

side note: the covid-dashboard app is also included in the main neo repo.
until the framework leaves the beta state, i am mostly working in there, since it is more convenient to work on the app & framework code base at the same time without the need for fetching it as a node module.

the uppercase path worked locally for me (macOS), but i can see how this causes trouble for other environments. closing this one.

in case you need an update on this repo (e.g. latest framework version), feel free to ping me on slack or open a ticket here.

**Comment by tobiu** [comment]
https://github.com/neomjs/neo/issues/500
